### ISSUE TITLE
请问可以支持v7a/32位吗？

### ISSUE THREAD

**Issue by nowexhas** [huage2580/reader_parser2#2]
从yuedu跟过来的，看了只有支持64位，但现在还有很多是v7a及32位，能否支持一下呢？因为没有go源无法自己打包，非常感谢！

**Comment by huage2580** [comment]
不打算支持

**Comment by huage2580** [comment]
https://github.com/huage2580/reader_ev_parser  
开放了仓库，有需要的话自己打包吧

**Comment by nowexhas** [comment]
> https://github.com/huage2580/reader_ev_parser 开放了仓库，有需要的话自己打包吧

收到，太感谢了
